name: Publish to PyPI

# This workflow publishes the package to PyPI when a GitHub Release is created.
# Setup required: Add PYPI_API_TOKEN to repository secrets (see SETUP_PYPI.md)

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          # This secret must be configured in repository settings -> Secrets and variables -> Actions
          # See SETUP_PYPI.md for setup instructions
          password: ${{ secrets.PYPI_API_TOKEN }}
